In [1]:
import numpy as np
import pandas as pd
import statistics
import matplotlib.pyplot as plt
from collections import Counter


K-Nearest Neighbors Classifier

In [25]:
class KNN_Classifier():
    # começar os parâmetros
    def __init__(self, distance_metric):
        self.get_distance_metric = distance_metric

    #distância entre os dados
    def get_distance_metric(self, training_data_point, test_data_point):
        if(self.distance_metric =='euclidean'):
            dist = 0 
            for i in range(len(training_data_point) -1):
                dist = dist +(training_data_point[i]-test_data_point
                              [i])**2
            euclidean_dist =np.sqrt(dist)
            return euclidean_dist  
        elif (self.distance_metric == 'manhattan'):
            dist = 0
            for i in range(len(training_data_point) - 1):
                dist = dist + abs(training_data_point[i]-test_data_point[i])
            manhattan_dist = dist
            return manhattan_dist
        
    #pegando o nearest neighboors           
    def nearest_neighbors(self, X_train, test_data, k):
        distance_list = []

        for training_data  in X_train:

            distance = self.get_distance_metric(training_data, test_data)
            distance_list.append(training_data,distance)

        distance_list.sort(key=lambda x:x[1]) 
        neighbors_list = []

        for j in range(k):
            neighbors_list.append(distance_list[j][0])

        return neighbors_list
    

    def predict(self,X_train,test_data,k):
        neighbors = self.nearest_neighbors(X_train,test_data,k)

        for data in neighbors:
            label = []
            label.append(data[-1])
        
        
        predicted_class = statistics.mode(label)
        return predicted_class




In [3]:
#carregando o data set
vinhos = pd.read_csv('winequality.csv')

In [4]:
vinhos.head()

Unnamed: 0  fixed acidity  volatile acidity  citric acid  residual sugar  \
0           0            5.9              0.61         0.08             2.1   
1           1            8.2              1.00         0.09             2.3   
2           2            6.4              0.24         0.49             5.8   
3           3            6.6              0.23         0.26             1.3   
4           4            7.2              0.24         0.29             3.0   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.071                 16.0                  24.0  0.99376  3.56   
1      0.065                  7.0                  37.0  0.99685  3.32   
2      0.053                 25.0                 120.0  0.99420  3.01   
3      0.045                 16.0                 128.0  0.99340  3.36   
4      0.036                 17.0                 117.0  0.99411  3.36   

   sulphates  alcohol  quality  wine_is_red  
0       0.77     11.1        6            1  
1       0.55      9.0        6            1  
2       0.98     10.5        6            0  
3       0.60     10.0        6            0  
4       0.68     10.1        6            0

In [5]:
vinhos.shape

(6497, 14)

In [6]:
X = vinhos.drop(columns='wine_is_red', axis =1)
Y = vinhos['wine_is_red']

In [7]:
X = X.to_numpy()
Y = Y.to_numpy()

In [8]:
print(X)
print(Y)

[[0.000e+00 5.900e+00 6.100e-01 ... 7.700e-01 1.110e+01 6.000e+00]
 [1.000e+00 8.200e+00 1.000e+00 ... 5.500e-01 9.000e+00 6.000e+00]
 [2.000e+00 6.400e+00 2.400e-01 ... 9.800e-01 1.050e+01 6.000e+00]
 ...
 [6.494e+03 7.900e+00 3.300e-01 ... 3.800e-01 8.800e+00 6.000e+00]
 [6.495e+03 7.000e+00 3.000e-01 ... 5.700e-01 1.140e+01 5.000e+00]
 [6.496e+03 6.400e+00 2.200e-01 ... 5.200e-01 1.010e+01 6.000e+00]]
[1 1 0 ... 0 0 0]


In [9]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state=2)

In [11]:
print(X.shape, X_train.shape, X_test.shape)

(6497, 13) (5197, 13) (1300, 13)


In [12]:
print(X_train)

[[8.600e+02 7.900e+00 1.600e-01 ... 5.100e-01 9.300e+00 7.000e+00]
 [6.303e+03 6.900e+00 2.000e-01 ... 5.600e-01 1.100e+01 6.000e+00]
 [6.261e+03 7.600e+00 4.200e-01 ... 5.700e-01 9.100e+00 5.000e+00]
 ...
 [4.635e+03 6.100e+00 2.700e-01 ... 4.700e-01 9.000e+00 5.000e+00]
 [2.018e+03 6.900e+00 1.800e-01 ... 5.400e-01 9.800e+00 6.000e+00]
 [1.847e+03 6.000e+00 2.400e-01 ... 5.400e-01 1.000e+01 7.000e+00]]


In [13]:
print(Y_train)

[0 0 1 ... 0 0 0]


In [14]:
X_train = np.insert(X_train, 13, Y_train, axis = 1)

In [15]:
print(X_train)

[[8.600e+02 7.900e+00 1.600e-01 ... 9.300e+00 7.000e+00 0.000e+00]
 [6.303e+03 6.900e+00 2.000e-01 ... 1.100e+01 6.000e+00 0.000e+00]
 [6.261e+03 7.600e+00 4.200e-01 ... 9.100e+00 5.000e+00 1.000e+00]
 ...
 [4.635e+03 6.100e+00 2.700e-01 ... 9.000e+00 5.000e+00 0.000e+00]
 [2.018e+03 6.900e+00 1.800e-01 ... 9.800e+00 6.000e+00 0.000e+00]
 [1.847e+03 6.000e+00 2.400e-01 ... 1.000e+01 7.000e+00 0.000e+00]]


In [16]:
X_train.shape

(5197, 14)

In [17]:
classifier = KNN_Classifier(distance_metric='euclidean')

In [24]:
prediction = classifier.predict(X_train, X_test[1], k=5)

print(prediction)

TypeError: 'str' object is not callable